config/routes.rb
require 'sidekiq/web'
require 'sidekiq_unique_jobs/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'conversations#new', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new'
    end
  end

  # Require authentication via devise and current_user be developer to view Sidekiq Web UI
  authenticate :user, ->(user) { user.developer? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show] do
    resources :memos
    resources :transcription_jobs, only: [] do
      resources :transcriptions, only: %i[index]
    end
    resources :transcription_downloads, param: :transcription_id, only: %i[show]
    resources :transcription_summaries, only: %i[create]
    resources :settings, only: %i[create update]
    resources :conversations, except: %i[show]
  end

  namespace :memos do
    resources :autosaves, only: %i[create update], param: :memo_id
  end

  resources :generate_text_requests, only: %i[create destroy] do
    member do
      get 'file'
    end
  end
  resources :generate_text_presets, except: %i[show]
  resources :generate_image_requests, only: %i[create]

  resources :blobs, only: %i[show], param: :active_storage_blob_id
  resources :blob_details, only: %i[show], param: :active_storage_blob_id
  resources :blob_previews, only: %i[show], param: :active_storage_blob_id
end

app/controllers/blob_details_controller.rb
class BlobDetailsController < ApplicationController
  def show
    @blob = ActiveStorage::Blob.associated_with_user(current_user.id)
                               .find(params[:active_storage_blob_id])
    respond_to(&:html)
  end
end

app/views/blob_details/show.html.haml
%turbo-frame{id: 'blob_details' }
  .blob-details.details-fields{ data: { controller: 'tooltip' } }
    - if @blob.generate_image_request
      .generate-image-details
        - gen_img_params = @blob.generate_image_request.parameterize
        .prompts
          %p Prompts
          - gen_img_params[:prompts].each do |prompt|
            = render ClipboardComponent.new(css_class: 'prompt') do |component|
              = component.with_copyable do
                %pre{ data: { 'clipboard-target' => 'source' } }= prompt['text']
                .prompt-weight.d-flex.align-items-center.justify-content-end.mt-3
                  %span.label.me-1 Weight
                  %pre.value= prompt['weight']
        .settings.d-flex.justify-content-between.flex-wrap
          - gen_img_params.slice(:style, :dimensions, :aspect_ratio).each do |k,v|
            %div.d-flex.align-items-center.justify-content-between.mt-3
              %span.label.me-2= k.to_s.titleize
              %pre.value= v
    .file-details
      %div.d-flex.align-items-center.justify-content-between.mt-3
        %span.label.me-2 Name
        %pre.value= @blob.filename
      %div.d-flex.align-items-center.justify-content-between.mt-3
        %span.label.me-2 Size
        %pre.value= number_to_human_size(@blob.byte_size)
    .download
      = link_to blob_path(@blob), data: { turbo: false, 'bs-toggle' => 'tooltip', 'bs-title' => t('download_image') } do
        %i.bi.bi-download.fs-3