config/routes.rb
require 'sidekiq/web'
require 'sidekiq_unique_jobs/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'conversations#new', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new'
    end
  end

  # Require authentication via devise and current_user be developer to view Sidekiq Web UI
  authenticate :user, ->(user) { user.developer? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show] do
    resources :memos
    resources :transcription_jobs, only: [] do
      resources :transcriptions, only: %i[index]
    end
    resources :transcription_downloads, param: :transcription_id, only: %i[show]
    resources :transcription_summaries, only: %i[create]
    resources :settings, only: %i[create update]
    resources :conversations, except: %i[show]
  end

  namespace :memos do
    resources :autosaves, only: %i[create update], param: :memo_id
  end

  resources :generate_text_requests, only: %i[create destroy] do
    member do
      get 'file'
    end
  end
  resources :generate_text_presets, except: %i[show]
  resources :generate_image_requests, only: %i[create]

  resources :blobs, only: %i[show], param: :active_storage_blob_id
  resources :blob_details, only: %i[show], param: :active_storage_blob_id
  resources :blob_previews, only: %i[show], param: :active_storage_blob_id
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :memo, optional: true
  belongs_to :user, optional: false

  # has_many :generate_text_requests, -> { order(:created_at) }, dependent: :destroy, inverse_of: :conversation

  has_many :turns, -> { order created_at: :asc }, class_name: 'ConversationTurn', dependent: :destroy,
                                                  inverse_of: :conversation
  accepts_nested_attributes_for :turns
  has_many :generate_image_requests, through: :turns, source: :turnable, source_type: 'GenerateImageRequest'
  has_many :generate_text_requests, through: :turns, source: :turnable, source_type: 'GenerateTextRequest'

  validates :title, presence: true, length: { maximum: 100 }

  validate :memo_user_matches_conversation_user, if: :memo_id_changed?

  # @param [String] prompt
  def self.title_from_prompt(prompt)
    prompt.truncate(40, separator: ' ')
  end

  def exchange
    generate_text_requests.completed.flat_map(&:to_turn)
  end

  def token_count
    generate_text_requests.sum(&:response_token_count)
  end

  private

  def memo_user_matches_conversation_user
    return if memo_id.blank?

    memo_user_id = Memo.where(id: memo_id).pluck(:user_id)[0]

    return if user_id == memo_user_id

    errors.add(:memo_id, 'must belong to the same user as the conversation')
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout 'conversations', except: :index
  layout 'application', only: :index

  before_action :set_conversation, only: %i[update destroy]

  def index
    relation = current_user.conversations
    relation = relation.where(memo_id: search_params[:q][:memo_id]) if search_params.dig(:q, :memo_id)
    @conversations, @cursor = Paginate.call(relation:, limit: 15, cursor: params[:c], order: { updated_at: :desc })

    respond_to do |format|
      format.html
      format.turbo_stream
      format.json do
        render json: @conversations.as_json(only: %i[id created_at updated_at]), status: :ok
      end
    end
  end

  def new
    @conversation = current_user.conversations.new
  end

  def create
    @conversation = current_user.conversations.new(new_conversation_params)
    set_user_id_on_turnable
    respond_to do |format|
      if @conversation.save
        enqueue_generate_text_job(@conversation.generate_text_requests.created.last)
        format.turbo_stream do
          redirect_to edit_user_conversation_path(current_user, @conversation), status: :see_other
        end
        format.json do
          render json: @conversation.as_json(only: %i[id memo_id created_at updated_at]), status: :created
        end
      else
        format.turbo_stream do
          flash.now.alert = t('unable_to_save', model_name: t('conversation.name'))
          flash_component = FlashMessageComponent.new(flash:, record: @conversation)

          render turbo_stream: [
                   turbo_stream.update(flash_component.id, flash_component),
                   turbo_stream.replace(
                     'prompt-form',
                     PromptFormComponent.new(conversation:).render_in(view_context)
                   )
                 ],
                 status: :unprocessable_entity
        end
        format.json do
          render json: { error: { message: @conversation.errors.full_messages.join(';') } },
                 status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @conversation = current_user.conversations
                                .includes(generate_text_requests: :generate_text_preset)
                                .find(params[:id])
  end

  def update
    @conversation.assign_attributes(conversation_params)
    set_user_id_on_turnable
    respond_to do |format|
      if @conversation.save
        generate_text_request = @conversation.generate_text_requests.created.last
        enqueue_generate_text_job(generate_text_request)
        format.turbo_stream do
          render 'conversations/update',
                 locals: { conversation: @conversation, generate_text_request: },
                 status: :ok
        end
        format.json do
          render json: @conversation.as_json(only: %i[id memo_id created_at updated_at]), status: :ok
        end
      else
        format.turbo_stream do
          flash.now.alert = t('unable_to_save', model_name: t('conversation.name'))
          flash_component = FlashMessageComponent.new(flash:, record: @conversation)

          render turbo_stream: [turbo_stream.update(flash_component.id, flash_component)],
                 status: :unprocessable_entity
        end
        format.json do
          render json: { error: { message: @conversation.errors.full_messages.join(';') } },
                 status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @conversation.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@conversation)
      end
      format.html { redirect_to user_conversations_path(current_user), notice: 'Conversation deleted' }
    end
  end

  private

  def enqueue_generate_text_job(generate_text_request)
    return unless generate_text_request

    GenerateTextJob.perform_async(generate_text_request.id)
  end

  def set_conversation
    @conversation = current_user.conversations.find(params[:id])
  end

  def set_user_id_on_turnable
    @conversation.turns.each { |t| t.turnable.user = current_user }
  end

  def search_params
    params.permit(q: %i[memo_id])
  end

  def new_conversation_params
    conversation_params.merge(title: Conversation.title_from_prompt(prompt))
  end

  def generate_text_requests_attributes
    conversation_params.dig(:turns_attributes, '0', :turnable_attributes)
  end

  def prompt
    generate_text_requests_attributes[:prompt]
  end

  def conversation_params
    params.require(:conversation).permit(
      :title,
      :memo_id,
      turns_attributes: [
        :turnable_type,
        turnable_attributes: [
          :prompt, :text_id, :temperature, :generate_text_preset_id, :model, :file
        ]
      ]
    )
  end
end

app/views/conversations/_title_form.html.haml
.title.d-flex.justify-content-center.align-items-center#conversation-title{ data: { controller: 'tooltip inline-edit' } }
  %div{ data: { 'inline-edit-target' => 'field' }}
    .title-field.fw-bold{ data: { action: 'click->inline-edit#onClickField', 'bs-toggle' => 'tooltip', 'bs-title' => conversation.title } }
      = truncate(conversation.title, length: 50, separator: ' ')
  = form_with model: [current_user, conversation], class: 'd-none', data: { 'inline-edit-target' => 'form' } do |form|
    .d-flex.justify-content-center.align-items-center
      = form.text_field :title, class: 'form-control me-1 title-input',
        data: { 'inline-edit-target' => 'input',
                action: 'change->inline-edit#save keypress.enter->inline-edit#blurInput:prevent blur->inline-edit#hideForm' }

app/views/conversations/edit.html.haml
= content_for :title do
  .conversation-title.container.mb-1.grid{ data: { controller: 'tooltip' } }
    .g-start-5.g-col-4
      = render partial: 'conversations/title_form', locals: { conversation: @conversation }
    .g-col-4.d-flex.align-items-center.justify-content-end
      - if @conversation.memo.nil?
        = button_to [current_user, @conversation], method: :delete, data: { turbo: false,
                                                'bs-toggle' => 'tooltip', 'bs-title' => t('conversation.delete') },
                                                class: 'btn icon-btn icon-btn-sm' do
          %i.bi.bi-trash3.text-danger
= render ConversationComponent.new(conversation: @conversation)

app/views/conversations/index.html.haml
.container.mt-2
  .grid.mb-4
    .g-col-6.mb-2
      = link_to 'New Conversation', new_user_conversation_path(current_user), class: 'btn btn-primary'
    .g-col-6
      = form_with(url: user_conversations_path(current_user), method: :get, class: 'form-inline justify-content-end') do |f|
        .input-group
          = f.text_field :query, placeholder: 'Search conversations', class: 'form-control'
          = f.submit 'Search', class: 'btn btn-outline-secondary'

  = render PaginationComponent.new(path: [:user_conversations_path, current_user]) do |pagination|
    = pagination.with_container do
      #conversations.list-group

app/views/conversations/index.turbo_stream.haml
= render PaginationComponent.new(cursor: @cursor, container_id: :conversations,
                                 path: [:user_conversations_path, current_user]) do |pagination|
  = pagination.with_list do
    - @conversations.each do |conversation|
      .list-group-item.list-group-item-action.d-flex.w-100.justify-content-between{ id: dom_id(conversation) }
        = link_to edit_user_conversation_path(current_user, conversation) do
          %h5.mb-1= truncate(conversation.title, length: 50, separator: ' ')
        .d-flex.justify-content-between.align-items-center
          .text-muted.me-3= conversation.updated_at.strftime('%B %d, %Y')
          = link_to user_conversation_path(current_user, conversation),
            class: 'float-end fs-5',
            disabled: conversation.memo_id.present?,
            data: { turbo_method: 'delete', turbo_confirm: t('confirm'),
                  'bs-toggle' => 'tooltip',
                  'bs-title' => t('delete', name: t('conversation.name')) } do
            %i.bi-trash3.text-black

app/views/conversations/new.html.haml
.new-conversation
  = render ConversationComponent.new(conversation: @conversation)

app/views/conversations/update.turbo_stream.haml
= turbo_stream.replace 'conversation-title' do
  = render partial: 'conversations/title_form', locals: { conversation: }, formats: [:html]
- if generate_text_request
  = turbo_stream.append 'conversation-turns' do
    = render ConversationTurnComponent.new(conversation_turn: generate_text_request.conversation_turn)
  = turbo_stream.replace PromptFormComponent::ID do
    = render PromptFormComponent.new(conversation:, last_request: generate_text_request)