config/routes.rb
require 'sidekiq/web'
require 'sidekiq_unique_jobs/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'conversations#new', as: :authenticated_root
    end

    unauthenticated do
      root 'users/registrations#new'
    end
  end

  # Require authentication via devise and current_user be developer to view Sidekiq Web UI
  authenticate :user, ->(user) { user.developer? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[show] do
    resources :memos
    resources :transcription_jobs, only: [] do
      resources :transcriptions, only: %i[index]
    end
    resources :transcription_downloads, param: :transcription_id, only: %i[show]
    resources :transcription_summaries, only: %i[create]
    resources :settings, only: %i[create update]
    resources :conversations, except: %i[show]
  end

  namespace :memos do
    resources :autosaves, only: %i[create update], param: :memo_id
  end

  resources :generate_text_requests, only: %i[create destroy] do
    member do
      get 'file'
    end
  end
  resources :generate_text_presets, except: %i[show]
  resources :generate_image_requests, only: %i[create]

  resources :blobs, only: %i[show], param: :active_storage_blob_id
  resources :blob_details, only: %i[show], param: :active_storage_blob_id
  resources :blob_previews, only: %i[show], param: :active_storage_blob_id
end

app/views/layouts/_flash.html.haml
.flash-message.d-flex.justify-content-center
  .alert-info= notice
  .alert-warning= alert
#alert-stream

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.bg-dark.p-0
  .container
    = link_to root_path, class: 'logo navbar-brand' do
      = render inline: Rails.application.assets.find_asset('tmp.svg').source
  - if current_user
    .container.collapse.navbar-collapse.justify-content-center{ data: { controller: 'my-channel' } }
      %ul.navbar-nav
        %li.nav-item
          = link_to "Memos", user_memos_path(current_user), class: 'nav-link text-light'
        %li.nav-item
          = link_to "Conversations", user_conversations_path(current_user), class: 'nav-link text-light'
        %li.nav-item
          = link_to "Settings", user_path(current_user), class: 'nav-link text-light'
  .container-fluid.justify-content-end
    - if current_user
      = link_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }
      = turbo_stream_from current_user, TurboStreams::STREAMS[:main]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tmp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = hotwire_livereload_tags if Rails.env.development?
  %body
    = render partial: 'layouts/nav'
    .container-sm
      = render partial: 'layouts/flash'
      = yield

app/views/layouts/conversations.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tmp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = hotwire_livereload_tags if Rails.env.development?
  %body
    .main.vh-100.d-flex.flex-column.overflow-hidden.position-relative
      = render partial: 'layouts/nav'
      = render partial: 'layouts/flash'
      = yield :title
      = yield